
spring:
  application:
    name: user
server:
  port: 8081

#  日志配置
logging:
  level:
    root: info
    com.us.trade: debug

## 老虎证券账户信息
tiger:
  server_url: https://openapi-sandbox.itiger.com/gateway
  account: DU575569
  standard_account: 164644
  paper_account: 20181212132721841
  tiger_id: 1
  private_key: MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBALVqZlrliwZOSWvLsMCxQE7BckKCuxlm0HbU8ibD/IuatupF+xLe9rC8yKAtZwLAgOcdr6Gl2l7N7R4cjBtnMnNQMa9EAtgr23cPynA9XGnBfU4XxF8cIzthC9I688+cce5VC8ppHs02bX9aa8ZcL2RUl2RhDuQKaHnayIWjLUwtAgMBAAECgYBVptyYgdO3sHKdwFe9QnKYPGET4eEwRwiZckS55MJxryQ5S70U1cwm+ZrHdWgzNmwlsjBf44xMQnF3TAciUQDSAQKMPAUrhDjar6m07hAAElBVILoj5063Y4hjby69PeuR6c47wpEgO3gXnY8V3vVl0HVppeLE5E5GrUx1IuLwSQJBAOK+IAH4vlH8dXHDG+pl8nnfQ60V3kiKlkL1hmVjUK1dYKa7z0srtRSUS41fIaw7HLPmMuoW41GyJ7kALbe18Q8CQQDM0wJrxrElZ89kgfi0attnUXcjjUFB2CnbMGZHsDJQwEOSWLzo7OYntBQIkD88nErjf8hhRabg5TlD5K9cKvcDAkEAlMGPVjvPARLUKlKK2fkQX4xuZfvW3ViuxDc4eQPzRgnhAwJsOTDvmBTCjHlBKjGN3yjDdniVol9zWBgZ5lDjWQJBAIKJDCbxxx4GrdbpOj6JR3DuK1aeBHPZNru5ecXAViC+l5HiOercZ8Xv70CR5atUFCou2t6bTEJR9A//436C508CQEUtu3vz8ylAYQNzuPK78oTkynjAwwNBDByH1Uu+wBnBYvKwHqtlamjeMh+n3NntzfM5gY0xYBmO0yY2REnwI4c=
  public_key: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCbm21i11hgAENGd3/f280PSe4g9YGkS3TEXBYMidihTvHHf+tJ0PYD0o3PruI0hl3qhEjHTAxb75T5YD3SGK4IBhHn/Rk6mhqlGgI+bBrBVYaXixmHfRo75RpUUuWACyeqQkZckgR0McxuW9xRMIa2cXZOoL1E4SL4lXKGhKoWbwIDAQAB








